# Generated by Django 2.2.28 on 2025-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LDAPTarget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=512)),
                ("username", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("group_base", models.CharField(max_length=1024)),
                ("user_base", models.CharField(max_length=1024)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
    ]
